FROM redis:latest

ARG REDIS_CONF
ENV REDIS_CONF=$REDIS_CONF

RUN mkdir /etc/redis/ && mkdir /var/log/redis/
COPY $REDIS_CONF /etc/redis/

RUN chown redis /etc/redis/redis.conf && \
    chgrp redis /etc/redis/redis.conf