FROM redis:latest

ARG REDIS_CONF
ENV REDIS_CONF=$REDIS_CONF

RUN mkdir /etc/redis/ && \
    mkdir /var/lib/redis/  && \
    mkdir /var/run/redis/

COPY $REDIS_CONF /etc/redis/

RUN chown redis:redis /etc/redis/redis.conf && \
    chown -R redis:redis /var/lib/redis/ && \
    chown redis:redis /var/run/redis